### ISSUE TITLE
WCEU slides for Tide within XWP section of booth

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#106]
Related to #104, we'll want to update our WCEU slides to tell the story about Tide.

**Comment by RobStino** [comment]
Joshua and I have talked about this and are setting a 24-hour deadline for coming up with a solution. With the deadline for implementation being 5 min before the event starts. :)

**Comment by jeffpaul** [comment]
Noting that @RobStino plans to work on this Sunday/Monday AUS-time.

**Comment by jeffpaul** [comment]
Closing this as it was completed and part of the XWP section of the Google booth.
