### ISSUE TITLE
update email used in production

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#113]
### Description

From Derek in Slack:
We'll need to setup a real email account to use later, I'm not a fan of my email being used for production

### Additional Information

We'll need to determine the best email to utilize and who should have access to that account.

**Comment by jeffpaul** [comment]
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1535487185000100) today, we're keeping this in the `1.0.0` release as we still need to setup SMTP to complete this issue.

**Comment by jeffpaul** [comment]
Note that this issue was [referenced in Slack](https://wordpress.slack.com/archives/C7TK8FBUJ/p1543354129119300).

**Comment by valendesigns** [comment]
Done
