### ISSUE TITLE
Further document maintainers, contributors, and guidelines for each

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#118]
### Description

All contributions are awesome, but not all are equal. I'd like to look at further defining maintainers (those active and with commit access) and contributors (so many ways to help, won't bother listing here), noting the responsibilities and differences between the two, and then having an updated Credits section (or renamed/reordered as makes sense) that highlights the maintainers and has appropriate space to thank and note all contributors.

### Additional Information

Some examples of how other repos handle this:
- [Sinatra's AUTHORS page](https://github.com/sinatra/sinatra/blob/master/AUTHORS.md)
- [p5.js' Contributors section](https://github.com/processing/p5.js?files=1#contributors)
- [WP-CLI's Contributing and Leadership sections](https://github.com/wp-cli/wp-cli#contributing)

**Comment by hellofromtonya** [comment]
The purpose of these sections and documents is to empower contribution while spreading the vision of the initiative.  Designing these sections can do a lot for Tide to attract, share, empower, and promote.

Part of this discussion is:

1. Sharing the vision and philosophy is critical to empower the community and align them to the initiative.
2. Sharing the process to help contributors know what to expect when they contribute. That includes sharing _how_ decisions are made and the process around discussion, roadmap, features, etc.
3. Providing guidance to _quickly empower_ developers to jump in and get contributing. Make it easy.
4. Giving credit to those who give of their time, energies, and expertise to help move the initiative forward.

Be as clear as possible while writing it to get people excited and involved.

>noting the responsibilities and differences between the two

Yes. But consider the reason for such sections.  It's not necessarily to define differences or responsibilities per se.  Yes, people want to know who's on the leadership team (maintainers), as it gives them confidence that this project will live up to its creed and mission.

It's not as important to draw a line of responsibilities or differences.  Think engaging, attracting, and empowering people to get involved.

I often read these sections and am left feeling like they are "words" without meaning or direction.  

Tide seeks to drive quality by providing a metric tool.  It's a powerful initiative that needs community adoption.  It needs draw in contributors and reach each end of the globe.

1. Put effort into making the Contributing section _attract_ and _guide_ potential contributors.  
2. Make them feel welcomed and appreciated. 
3. Get people excited about the benefits of Tide.
4. Give them guides that empower them to quickly contribute. 

>then having an updated Credits section (or renamed/reordered as makes sense) that highlights the maintainers and has appropriate space to thank and note all contributors.

I really dig the [p5.js Contributors section](https://github.com/processing/p5.js?files=1#contributors) as the images _pop_, showing off each person with their profile and name.  Why? The faces give personality to the project, giving the feel of a community.

**Comment by jeffpaul** [comment]
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1535487529000100) today, we're keeping this in the `1.0.0` release as this work will ideally complete during this cycle.

**Comment by jeffpaul** [comment]
Note that this issue was [referenced in Slack](https://wordpress.slack.com/archives/C7TK8FBUJ/p1543352856085900).

**Comment by valendesigns** [comment]
This has been address in the 1.0.0-bet2 branch.
