### ISSUE TITLE
Create private Kubernetes Clusters

### ISSUE THREAD

**Issue by valendesigns** [wptide/wptide#121]
In order to secure the services and also not use the limited IP addresses we need to create private Kubernetes clusters as they have no need to be exposed to the open internet.

https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters

**Comment by jeffpaul** [comment]
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1535487644000200) today, we're moving this to `Future Release`.

**Comment by valendesigns** [comment]
It's not needed, closing for now.
