### ISSUE TITLE
blog post on lessons learned migrating to GCP

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#124]
### Description

Similar to https://www.wpzoom.com/news/migrating-to-easy-digital-downloads/, we should look to summarize and share our learnings on migrating to GCP for others to benefit from.

### Additional Information

- [ ] draft outline of post
- [ ] add technical details to outline
- [ ] add imagery/gifs to support post

**Comment by hellofromtonya** [comment]
Another idea is to develop different types of content, each capturing and sharing your perspectives.

Why?

1.  People relate and connect to various mediums differently.  Some like blog posts.  Others interviews.  Other webinars. You get the point.
2.  Different stories and experiences will resonant with a more diverse demographic.

Lessons learned and the stories behind each are powerful and valuable. Maximize the opportunity to reach as many people as possible.

**Comment by rheinardkorf** [comment]
Thanks @hellofromtonya 

I wouldn't mind at some stage sharing the reasoning from moving from PHP to Go for the services and how the WP REST API has been a nice way for us to still use WordPress despite building services in another language.

**Comment by hellofromtonya** [comment]
@rheinardkorf Bingo, that’s a value share for the community. Sharing _the why_ of the reasoning(s) provides the opportunity to open someone else’s mind, giving them insights into how this team thinks.

Tip:  Start with the technical challenge to be solved.  Then walk into the reasoning behind the decisions and solution.  Share the why.  Share the why not for alternatives. Then give the actualized benefits.

**Comment by jeffpaul** [comment]
Another related item that this Issue could evolve into (or become a parallel Issue) is creating a GCP whitepaper focused on the AppEngine architecture for setting up WordPress.

**Comment by jeffpaul** [comment]
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1535487725000200) today, we're moving this to `Future Release`.

**Comment by jeffpaul** [comment]
@rheinardkorf would you be open to someone chatting with you on that topic, drafting a blog post on make/tide, and then you working on final edits to share a post on that topic?

**Comment by jeffpaul** [comment]
Given how long it's been since the GCP migration and our focus being on 1.0.0, I'm going to close this issue.  Should someone have time to work on some marketing efforts, we can re-open this or a new issue and track things there.
