### ISSUE TITLE
minimize README now that content is on docs site

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#133]
### Description

Now that the documentation website is active at www.wptide.org and it contains most of the content in the [README](https://github.com/wptide/wptide/blob/develop/README.md) we should look to remove the duplicative content from the README and include an appropriately worded link to the docs site.

**Comment by jeffpaul** [comment]
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1535487895000100) today, we're keeping this in the `1.0.0` release.

**Comment by jeffpaul** [comment]
Note that this issue was [referenced in Slack](https://wordpress.slack.com/archives/C7TK8FBUJ/p1543352595077800).

**Comment by jeffpaul** [comment]
Per discussion with @valendesigns at WCUS Contributor Day today, the updated plan is to pull in all the additional docs from wptide.org to the wptide repo's readme (and markdown files in a directory).  Then we'll look to replace the docpress theme/build process with something different to publish the docs markdown files up to wptide.org so the documentation site is current and accurate.

**Comment by jeffpaul** [comment]
Update that we're going to reduce the README to Tide local install instructions, everything else will be in the docs and wptide.org.

**Comment by valendesigns** [comment]
This is fixed in the `1.0.0-beta2` branch.
