### ISSUE TITLE
investigate dropping `glide` for `dep`

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#136]
### Description

From @rheinardkorf: If we do this we can make it even more user friendly by removing the Go requirement and building in the official `_/go` container.

**Comment by jeffpaul** [comment]
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1535487974000100) today, we're keeping this in the `1.0.0` release as a `nice to have`.

**Comment by jeffpaul** [comment]
Note that this issue was [referenced in Slack](https://wordpress.slack.com/archives/C7TK8FBUJ/p1543354193121800).

**Comment by jeffpaul** [comment]
Per discussion in Slack, we're punting this to `Future Release` though I do like the idea as I believe this opens up some automated dependency updates via [GitHub’s probot](https://probot.github.io/) issuing PRs as dependencies get updated.

**Comment by valendesigns** [comment]
Closing this issue, we will continue on as they are with Glide. If we ever update Go then I'll reopen this.
