### ISSUE TITLE
make build.images fails from malformed child dependency 'chromium@community'

### ISSUE THREAD

**Issue by zachskaggs** [wptide/wptide#142]
### Description
make build.images fails from malformed child dependency

### Steps to Reproduce

When running make build.images I get this error before the script stops:

ERROR: 'chromium@community' is not a valid child dependency, format is name([<>~=]version)
The command '/bin/sh -c echo "@community http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories     && apk add --no-cache --upgrade --virtual .build-deps        apk-tools         nodejs-npm     && apk add --no-cache --update --virtual .persistent-deps         chromium@community         grep         nodejs         ttf-freefont      udev     && npm i -g npm     && npm i -g lighthouse@next     && runDeps="$(         scanelf --needed --nobanner --recursive /usr/local             | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }'             | sort -u             | xargs -r apk info --installed             | sort -u     )"     && apk add --virtual .run-deps $runDeps     && apkdel .build-deps     && rm -rf /var/lib/apk/lists/* /usr/share/doc/* /usr/share/man/* /usr/share/info/* /var/cache/apk/*     && chmod +x /usr/bin/lh     && mkdir -p /srv/data' returned a non-zero code: 255
make: *** [lighthouse.build.image] Error 255

### Additional Information

OSX 10.13.5

**Comment by grappler** [comment]
I can confirm I got this error too.

**Comment by jeffpaul** [comment]
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1535488397000100) today, we're keeping this in the `1.0.0` release as it's in progress and fixed in the branch @valendesigns is working on.

**Comment by matt-ward** [comment]
I got this too. I fixed it by editing the Docker file in /service/lighthouse-server/docker. I changed `chromium@community` to just `chromium` This resolved the issue for me.
