### ISSUE TITLE
add WPCS version number to schema and API

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#144]
### Description

We don't currently keep track of the WPCS version of each audit, which will become a problem when we bump to WPCS 1.0 and can no longer discern which version of WPCS was used when getting results from the API.

**Comment by jeffpaul** [comment]
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1534882520000100) today, we're tagging this to the `1.0.0` release

**Comment by jeffpaul** [comment]
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1535488447000100) today, we're keeping this in the `1.0.0` release.

**Comment by jrfnl** [comment]
Just saw this issue in the bug scrub.

Some questions:
* Is the version of PHPCompatibility available via the API ? Might be more relevant at this time as those are the checks you are currently using.
* How would you retrieve the version nr of WPCS/PHPCompatibility ? This info is currently not available via PHPCS itself.

**Comment by jeffpaul** [comment]
Note that this issue was [referenced in Slack](https://wordpress.slack.com/archives/C7TK8FBUJ/p1543353843111800).

**Comment by jeffpaul** [comment]
Per discussion in Slack, we're punting this to `Future Release` when we'll have more time to focus on this issue.

**Comment by valendesigns** [comment]
We have some `ENV`'s in the Dockerfile that we can use to generate this info. I just need to add a new field to the Go struct and send it with the payload. It should be pretty easy.

**Comment by pierlon** [comment]
Working on this.

**Comment by jrfnl** [comment]
Loosely related: https://github.com/squizlabs/PHP_CodeSniffer/issues/2600

**Comment by derekherman** [comment]
This has been completed in #196
