### ISSUE TITLE
Update WPCS to v1.0+

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#145]
### Description

As WPCS has recently bumped to 1.0, we'll want to bump accordingly, but this work will have #144 as a dependency so that we can support details on which version of the standard is used on a specific audit.

### Additional Information

Relates to #116.

Also, per @jrfnl... re: upgrading to WPCS 1.0.0 - also don't forget to change from using `PHPCompatibility` to `PHPCompatibilityWP` (if that hasn't been done already)

**Comment by jeffpaul** [comment]
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1535488471000100) today, we're keeping this in the `1.0.0` release as it's in progress but not sure if there are any issues.  We'll need to get the updated PHP_CodeSniffer working first.

**Comment by jrfnl** [comment]
See my comment in https://github.com/wptide/wptide/issues/116#issuecomment-416885336 - PHPCS upgrade is not a blocker for upgrading WPCS.
