### ISSUE TITLE
Interface for displaying PHP Compatibility results

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#152]
@jwold commented on [Tue Dec 19 2017](https://github.com/wptide/tide-issues/issues/1)

The following sketches represent options for displaying the PHP Compatibility results within the plugin interface on WordPress.org.

Would love feedback from others on which of these options makes the most sense, and whether there are other options we should be considering for displaying the information.

<img width="1366" alt="option 1b" src="https://user-images.githubusercontent.com/3411173/34182962-37a80818-e4cd-11e7-9d39-c1242ab048db.png">

------ ----- ----- ----- ------ ----- ----- ----- ------ ----- ----- -----

<img width="1366" alt="option 3b" src="https://user-images.githubusercontent.com/3411173/34182960-3771ab24-e4cd-11e7-90a9-3c82827bed46.png">

------ ----- ----- ----- ------ ----- ----- ----- ------ ----- ----- -----

<img width="1366" alt="option 4" src="https://user-images.githubusercontent.com/3411173/34182961-378fd892-e4cd-11e7-8e02-a6ff7e4c27df.png">

---

@rheinardkorf commented on [Tue Dec 19 2017](https://github.com/wptide/tide-issues/issues/1#issuecomment-352913360)

@jwold I'd still prefer a tick actually..... maybe a different colored tick? The info icon makes me feel worried..... "is it or isn't it compatible?"

---

@jwold commented on [Tue Dec 19 2017](https://github.com/wptide/tide-issues/issues/1#issuecomment-352914306)

Since in Option 4 we're suggesting NO Checkmarks for 0 warnings, 0 errors, what about gray checkmark for other situations? https://developer.wordpress.org/resource/dashicons/#yes

---

@rheinardkorf commented on [Tue Dec 19 2017](https://github.com/wptide/tide-issues/issues/1#issuecomment-352917597)

@jwold can we have the options labeled so that we can comment towards them. Its not easy seeing which one Option 4 is.

---

@jwold commented on [Mon Dec 25 2017](https://github.com/wptide/tide-issues/issues/1#issuecomment-353904554)

@rheinardkorf I had labeled them here: http://d.pr/i/RJwiLU, is that ok? 

---

@philipjohn commented on [Tue Jan 09 2018](https://github.com/wptide/tide-issues/issues/1#issuecomment-356431896)

Second option is my preference - I think it fits in with the structure of the plugin pages more generally, and is visually more indicative to the viewer as to what's going on at a glance.

---

@jwold commented on [Tue Jan 23 2018](https://github.com/wptide/tide-issues/issues/1#issuecomment-359944122)

Based on feedback and discussion I'd like to propose the following two mockups (Development-tab and Details-tab) for feedback.

1. Green areas are new things we'd be adding in (1., 2., 4., on the mockup)
2. Red - Things we would remove (3., 5., on the mockup)
3. Orange - Things still being worked on (The note and the ideas to simplify errors/warnings)

![details-tab](https://user-images.githubusercontent.com/3411173/35302888-f903285c-0044-11e8-93f5-c08a3463170c.png)

![development-tab](https://user-images.githubusercontent.com/3411173/35302889-f91c5a20-0044-11e8-9b9f-e327f791801a.png)

---

@jrfnl commented on [Wed Jan 24 2018](https://github.com/wptide/tide-issues/issues/1#issuecomment-360223429)

Just my two cents: I think mentioning the "The following versions pass with no errors" could give people the confidence they might need to attempt an upgrade. Positive reinforcement and such.
Though I should also note that not everything can be detected with PHPCompatibility, so no errors is no guarantee that all will be good....

---

@00travelgirl00 commented on [Tue Jan 30 2018](https://github.com/wptide/tide-issues/issues/1#issuecomment-361755508)

My favourite would be 2b from the first sketch. 
I think in this case its important to have a balance to educate users and give them confidence, but also to have a tool for developers. 

So I think to show the check for the multiple php levels with yes, no, not checked and a tab with details would be ideal in my eyes. 

---

@karmatosed commented on [Mon Mar 05 2018](https://github.com/wptide/tide-issues/issues/1#issuecomment-370570196)

Firstly, good flow on this and it's come quite a way. I would like to give a little feedback on a couple of things I think we should focus on a bit more.

For example, I think it's important to have 'scalability' of the results. I know we are juggling some intense content, but we can make sure it's obvious enough at a glance. To that point, what glanceable content do we need users to get?

We are in danger of having a river of content in the main area. Do 'Contribution & Developers' belong with 'PHP Compatibility'?

I would simply what we show without the user digging more. For example do they care about multiple PHP versions or do they just need to know it's up to date?

---

@jwold commented on [Mon Mar 12 2018](https://github.com/wptide/tide-issues/issues/1#issuecomment-372533272)

Thank you everyone for such great feedback. Really appreciate it. I’ll address each piece and then share an updated mockup. 

1. Updating text to read like “The following versions pass with no errors”. I made a modification to the text to make it a bit closer to this. Great feedback. 

2. “show the check for the multiple php levels with yes, no, not checked and a tab with details would be ideal in my eyes.” I took a stab at playing with this idea as shown in the mockup. 

3. Scalability of results - Yes. This is a problem. I think switching to a tab interface for the PHP versions will help. 

4. Having a modal popup on the sidebar for the PHP version - Scrapped that, adds too much complexity. 

5. “We are in danger of having a river of content in the main area.” Yes, this is a concern. Hoping the updated mockup gets us closer to solving this problem, but welcome feedback!

6. “I would simply what we show without the user digging more. For example do they care about multiple PHP versions or do they just need to know it's up to date?”. I think having the sidebar callout the minimum version, and then clicking for more and seeing a tab interface with checkboxes will help users have confidence they can go forward. 

LINK TO UPDATED MOCKUP: https://xd.adobe.com/view/b615e0e9-57a6-4cec-a080-adf9f40b24b4
Video walkthrough: https://v.usetapes.com/5APKX1CsIT

---

@karmatosed commented on [Wed Mar 21 2018](https://github.com/wptide/tide-issues/issues/1#issuecomment-375091985)

Thanks for tackling this and responding well to feedback @jwold, I think it is certainly getting there.  

> Scalability of results - Yes. This is a problem. I think switching to a tab interface for the PHP versions will help.

I have to say I am cautious of double tabs on a page. Have you considered other things like a collapsed accordion going down the page? This may have the added benefit of working better on smaller devices.

There's still a lot of content, maybe we can use jump to headers? Although also judging seeing accordions may help.

One little point, I think we need to be careful when it's made the icon makes sense incases of color being removed, I think it does but just a note for clarity.

---

@jwold commented on [Mon Mar 26 2018](https://github.com/wptide/tide-issues/issues/1#issuecomment-376251227)

@karmatosed thanks for the feedback!

1. The collapsed accordions were one of the first ideas I played with, and I wondering if that'd be too much clicking to expand/collapse. Example: https://d.pr/i/2PKFKJ

Agreed though that the collapsed accordion makes more sense on mobile. So, my CTA would be to update it to the screenshot above. Agreed?

2. Icons, agreed; want to make sure they work when colors aren't present. 

---

@karmatosed commented on [Mon Mar 26 2018](https://github.com/wptide/tide-issues/issues/1#issuecomment-376295614)

> I wondering if that'd be too much clicking to expand/collapse. Example: https://d.pr/i/2PKFKJ

I think it's just as much to click each tab perhaps?

---

@jwold commented on [Mon Apr 09 2018](https://github.com/wptide/tide-issues/issues/1#issuecomment-379964345)

@karmatosed thought this over and chatted with a few folks (thanks @RobStino and Leo) and wanted to try an accordion that displays some default information.

So instead of a open/closed state, we could have partially open and all the way open. 

In the partially open state we could surface the type of errors (would need input from @valendesigns on how well this could work), and then when you click "show all" we'd see the full list of warnings, errors, etc.

Feedback/thoughts? 

<img width="1176" alt="my sketches - 2018-04-09 19 57 38" src="https://user-images.githubusercontent.com/3411173/38535021-688863cc-3c36-11e8-97d9-da778efd4e59.png">

---

@karmatosed commented on [Tue Apr 10 2018](https://github.com/wptide/tide-issues/issues/1#issuecomment-380176879)

I think 'show all' does help a little. Because this is such a complex page could we see a mock with it in situation?

---

@jwold commented on [Tue Apr 10 2018](https://github.com/wptide/tide-issues/issues/1#issuecomment-380194732)

I think you're asking if the mockup could include some live data showing real errors in warnings? If so great idea! Will followup on that. 

---

@postphotos commented on [Tue Apr 10 2018](https://github.com/wptide/tide-issues/issues/1#issuecomment-380241029)

@jwold - I think the question is what does this screen mean? To recap, I see there's three points of data about each error:

1. The kind of error
2. In what file it appears in
3. What lines on that file that error appears on

The summary/unexpanded view yields most value if it yields the kinds of errors and the overall frequency of that kind of error across the full plugin/theme, and the expanded view giving context based on types of errors and where they appear.

Real errors would definitely illustrate this much clearer!

---

@jeffpaul commented on [Fri Jun 01 2018](https://github.com/wptide/tide-issues/issues/1#issuecomment-393932414)

Remaining work here as I see it:
- [ ] get example PHP Compat results
- [ ] update mock to include example results
- [ ] final UX review from Core Design team
- [ ] final UX review from community + Matt
- [ ] create a Meta Trac ticket to cover the actual .ORG integration work

Anything changes/additions to that list?

---

@jeffpaul commented on [Tue Aug 28 2018](https://github.com/wptide/tide-issues/issues/1#issuecomment-416805157)

Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1535488572000300) today, we're keeping this in the `1.0.0` release.  Note that it directly relates to https://github.com/wptide/wptide/issues/90.

**Comment by jeffpaul** [comment]
Note that this issue was [referenced in Slack](https://wordpress.slack.com/archives/C7TK8FBUJ/p1543352885086900).

**Comment by jeffpaul** [comment]
@jwold if your current designs aren't on this issue, would you please share them here and then create a Meta Trac ticket to cover the implementation of displaying PHP Compatibility results from Tide on wp.org?  Note that as of now we don't have warnings, just errors in the summary report in Tide.  Once the Meta Trac ticket is created, please link to it from this issue and then close this issue as we'll monitor development with the Meta team via their Trac ticket... thanks!

**Comment by jwold** [comment]
@jeffpaul dropping in the latest design here. They haven't been updated in quite a while. 

![Group](https://user-images.githubusercontent.com/3411173/54780488-1ee6ba00-4bd7-11e9-9987-9c54052d1cb5.png)

![Group 2](https://user-images.githubusercontent.com/3411173/54780489-1ee6ba00-4bd7-11e9-91f2-0c5b98dc2b08.png)

Created a placeholder Trac ticket on Meta. Thanks!

https://meta.trac.wordpress.org/ticket/4309

**Comment by jeffpaul** [comment]
Closing this work as complete on our end, remaining integration work will be handled via the Meta team using these designs and our API coming in the 1.0.0 release to display this data on .ORG.
