### ISSUE TITLE
apply Tide against custom plugins and themes

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#159]
@jeffpaul commented on [Wed Jun 13 2018](https://github.com/wptide/tide-issues/issues/9)

From @gravnetic via [comment on the Tide > WordPress post](https://xwp.co/tide-joins-wordpress/#comment-1211), I'm adding a placeholder issue to track discussion around enhancing Tide to support the auditing of custom plugins and themes (i.e., ones not available on WordPress.org).

---

@jeffpaul commented on [Tue Aug 28 2018](https://github.com/wptide/tide-issues/issues/9#issuecomment-416808460)

Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1535489171000100) today, we're moving this to `Future Release`.

**Comment by valendesigns** [comment]
It already supports this. All that is required is a Tide API user account.
