### ISSUE TITLE
After migrating repos there is an issue with the refresh tokens in the API plugin

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#161]
Originally reported by @rheinardkorf on 06/Apr/17 7:26 PM:

Temporarily commenting out the following in class-plugin.php:

{code:php}
// $this->components['user_refreshtoken'] = new User_RefreshToken( $this ); // Enabled user-based refresh tokens.
{code}

This needs proper debugging and fixing, but is not essential to the immediate work. From what I remember that was commented out because tokens weren't getting refreshed. The best way to test this would be with some unit testing. I would keep this item in the backlog, but its not a blocker at the moment.

**Comment by valendesigns** [comment]
Fixed in this commit https://github.com/wptide/wp-tide-api/commit/2e95491a75725f46b3d2644f28c29c7d40e87b22
