### ISSUE TITLE
Windows 10 : OCI runtime exec failed: the input device is not a TTY.

### ISSUE THREAD

**Issue by ronakganatra9** [wptide/wptide#168]
### Description

I am installing tide on my local windows 10. I have run followed command.
make api.tpl - Success
make api.composer - success
make api.up- success 
make api.setup - error

While trying to run make api.setup It gives me following error:
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
make: *** [api.setup] Error 1

then i tried using : winpty make api.setup but I got following error.
OCI runtime exec failed: exec failed: container_linux.go:348: starting container
 process caused "no such file or directory": unknown
make: *** [api.setup] Error 126

Here is the screenshot: [Screenshot](https://www.screencast.com/t/sXrMRGWz7O)

### Steps to Reproduce

Installed all dependencies in windows.
the issue happens while running a command make api.setup

**Expected behavior:** [What you expect to happen]
Runs Fine
**Actual behavior:** [What actually happens]
Issues as mentioned above.

While trying to run make api.setup It gives me following error:
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
make: *** [api.setup] Error 1

then I tried using: winpty make api.setup but I got following error.
OCI runtime exec failed: exec failed: container_linux.go:348: starting container
 process caused "no such file or directory": unknown
make: *** [api.setup] Error 126
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Additional Information

All the other dependencies are installed and verified and installed all the latest dependencies.

**Comment by jeffpaul** [comment]
Note that this likely relates to #100

**Comment by valendesigns** [comment]
You have to be running the API when you attempt to run the setup script. So that means you need to have two shells open, one that you do `make api.up` and another that you do `make api.setup` after the API responds in the other shell with this:

```api-php_1 | [27-Feb-2019 05:54:46] NOTICE: ready to handle connections```

@ronakganatra9 can you confirm this is still an issue?

**Comment by valendesigns** [comment]
Closing. We can reopen if it's still an issue.
