### ISSUE TITLE
Add favicon to the docs site

### ISSUE THREAD

**Issue by valendesigns** [wptide/wptide#176]
## Issue Overview
We need to add a favicon of the Tide icon to the docs site.

## Steps to Reproduce (for bugs)
Open a browser, navigate to https://wptide.og

## Expected Behavior
I see a favicon 😉 

## Current Behavior
I do not see a favicon 🤣 

## Possible Solution
You can easily add a favicon to the customizer — just need the image.

## Todos
- [x] Create a 512px png favicon
- [x] Add the favicon to the Customizer

**Comment by cathibosco** [comment]
Here you go! Cheers @jeffpaul @valendesigns 
![tide-icon-512x512](https://user-images.githubusercontent.com/4819761/54235280-45299d00-44e7-11e9-8856-0672f572e1d3.png)

**Comment by valendesigns** [comment]
Thank you @cathibosco I've added it to the site.
