### ISSUE TITLE
Extend the JSON output to inclide 'incompatible_versions'

### ISSUE THREAD

**Issue by ottok** [wptide/wptide#184]
## Current Behavior

Currently the JSON output includes this:
```
        "compatible_versions": [
          "5.6",
          "7.0",
          "7.1",
          "7.2"
         ],
```

There is however no indication of what versions was tested or what versions the plugin/theme is *NOT* compatible with.
        ]

## Possible Solution

Extend the JSON output to have a 'incompatible_versions' field. Then the output would be something like:
```
        "compatible_versions": [
          "5.6",
          "7.0",
          "7.1",
          "7.2"
         ],
        "incompatible_versions": [
          "5.2",
          "5.3"
         ],
```

As a side note please start testing for PHP 7.3 compatibility as well, and for PHP 7.4 as soon as the ruleset is out.

**Comment by ottok** [comment]
The API seems to be generated via https://github.com/wptide/pkg/blob/master/tide/tide.go. I tried to figure out how to fix this myself but the code layout has so many abstractions that I can't follow it.

**Comment by ottok** [comment]
I scanned through wp-tide-api and it does not have the string `compatible_versions` anywhere, so I suspect no changes is needed to that plugin.

Somebody who has the full pipeline set up on their computer should test my patch in https://github.com/wptide/pkg/pull/19 if it actually works.

**Comment by jeffpaul** [comment]
@ottok welcome to Tide and thanks for the feedback!  I agree that makes sense to include the incompatible versions that we've tested as well, thanks for calling this out and working towards a solution.

**Comment by jeffpaul** [comment]
@ottok note the recently merged PR, please confirm that it appears updated properly now... thanks!
