### ISSUE TITLE
Update PHPCompatibility and related dependencies

### ISSUE THREAD

**Issue by jrfnl** [wptide/wptide#193]
### Dependencies are out of date

Most PHP_CodeSniffer related dependencies are out of date.

https://github.com/wptide/wptide/blob/ed9f15907c9c865e92f84843a7a53e7ec3a8e06d/service/phpcs-server/docker/Dockerfile#L6-L12

Latest releases:
* PHP_CodeSniffer: [3.5.0](https://github.com/squizlabs/PHP_CodeSniffer/releases)
* PHPCompatibility: [9.3.1](https://github.com/PHPCompatibility/PHPCompatibility/releases) - Note: 9.3.2 will probably be released next week.
* PHPCompatibilityWP: [2.1.0](https://github.com/PHPCompatibility/PHPCompatibilityWP/releases)
* PHPCompatibilityParagonie: [1.1.0](https://github.com/PHPCompatibility/PHPCompatibilityParagonie/releases) - Note: 1.2.0 will probably be released next week.
* PHPCompatibilityPasswordCompat: [1.0.2](https://github.com/PHPCompatibility/PHPCompatibilityPasswordCompat/releases)
* PHPCompatibilitySymfony: [1.1.1](https://github.com/PHPCompatibility/PHPCompatibilitySymfony/releases)

In other words, only WPCS is currently at the latest version, though you can expect a new release of that as well over the next few weeks.

Using the latest version of, especially, the PHPCompatibility rulesets is highly recommended as:
1. More checks get added regularly, making the scans more comprehensive.
2. Bugs/false positives get fixed as soon as they get reported most of the time, so using the latest versions also reduces the number of false positives reported by the scans.

#### Not letting Composer manage dependencies

https://github.com/wptide/wptide/blob/ed9f15907c9c865e92f84843a7a53e7ec3a8e06d/service/phpcs-server/docker/Dockerfile#L30-L36

It looks like all of the PHPCS repos are individually required and set to a specific version.
Unless you actually call any of the code in any of these standards directly, this is not recommended as it will easily lead to a conflicting versions hell.

`PHPCompatibility` is a dependency of `PHPCompatibilityWP`, `PHPCompatibilityPasswordCompat` and `PHPCompatibilitySymfony`.
Similarly, `PHPCompatibilityParagonie` and `PHPCompatibilityPasswordCompat` are dependencies for `PHPCompatibilitySymfony`.

As far as I can see, they are not direct dependencies for Tide. So instead of setting the version for them yourself, let `PHPCompatibilityWP` and `PHPCompatibilitySymfony` manage these.

You could even go so far as to just include the [`PHPCompatibilityAll`](https://github.com/PHPCompatibility/PHPCompatibilityAll) package instead of all the individual ones.

Why use Composer as a dependency manager if not for _actually letting it manage the dependencies..._ ?

I'm even tempted to say _don't require PHP_CodeSniffer, but let WPCS and PHPCompatibility manage the version for that_, but I suspect that Tide may call PHPCS code directly, in which case, it is a direct dependency.
If not...

#### Not using the DealerDirect Composer plugin

https://github.com/wptide/wptide/blob/ed9f15907c9c865e92f84843a7a53e7ec3a8e06d/service/phpcs-server/docker/Dockerfile#L39

Currently the PHPCS `installed_paths` setting is set via a hard-coded directive. This does not allow for additional rulesets being added to any of the included external PHPCS standards without making manual changes to the command.

The [DealerDirect Composer PHPCS plugin](https://github.com/Dealerdirect/phpcodesniffer-composer-installer) can sort this out for you automatically and is highly recommended to use instead.

Note: as of the next majors, both WPCS as well as PHPCompatibility will make this plugin one of their dependencies and will start including an additional external standard, so keeping this as a manual thing is really just asking for problems.

## Possible Solution
* Update the dependencies.
* Remove dependencies which are not *your* dependency.
* `composer require` the DealerDirect Compose PHPCS plugin.

**Comment by jeffpaul** [comment]
Thanks for the wonderfully detailed issue @jrfnl, we'll look to review this during Tidechat and hopefully get someone assigned to handling this!

**Comment by jrfnl** [comment]
Note: while the out-of-date versions have now been addressed, the manual setting of `installed_paths` and the fact that Composer is not allowed to properly manage dependencies, has not (been addressed).

**Comment by derekherman** [comment]
We need to explicitly track the versions, they are being used as part of the Tide API response now. So when an audit happens we know which version of PHPCS and the associated standard was executed. So that part of the task is not likely to be changed.
