### ISSUE TITLE
Remove outdated ruleset

### ISSUE THREAD

**Issue by jrfnl** [wptide/wptide#194]
The ruleset as found here: https://github.com/wptide/wptide/tree/7a9890d291cdd96ff0161aecfcb920cea1c37d56/cmd/phpcs-server/testdata

... should no longer be used and should be removed. If anything, it should be replaced by just using `PHPCompatibilityWP`.

**Comment by jeffpaul** [comment]
Thanks for calling this out @jrfnl, we'll work to get someone assigned to swapping this ideally ahead of Tide's 1.0 release!

**Comment by derekherman** [comment]
The custom ruleset only exists to test that we can override a ruleset not that it's used in production. I don't believe we need to do anything here.

**Comment by jrfnl** [comment]
> The custom ruleset only exists to test that we can override a ruleset not that it's used in production. I don't believe we need to do anything here.

Glad to hear it, though most people won't realize this when they come across it and may take it as a "good example".

Would be great if we could avoid that situation.

Suggestions:
* Add a BIG WARNING as a comment in the file and point to the `PHPCompatibilityWP` repo.
* Update the ruleset to a more realistic example using `PHPCompatibilityWP`.
    If I understand you correctly, the content shouldn't matter that much as it's just testing that it's being overruled ?

**Comment by derekherman** [comment]
Yes, correct it’s just for testing. We can change the file to be a more accurate example.
