### ISSUE TITLE
Audit servers generate identical checksums for multiple projects

### ISSUE THREAD

**Issue by danlouw** [wptide/wptide#28]
Steps to reproduce:

- Run the Sync Server locally to populate the SQS queues for Themes and Plugins (including Lighthouse)
- Run the PHPCS and Lighthouse server locally to work through items in the queues

Results:
```
phpcs-server_1       | 2018/03/08 05:24:37 i-amaze: Project checksum: `f8ac35b4ae08ab4969b67acc588807f8254d506ee578bf537c1017b7d9650ac4`
...
phpcs-server_1       | 2018/03/08 05:24:52 Avior: Project checksum: `f8ac35b4ae08ab4969b67acc588807f8254d506ee578bf537c1017b7d9650ac4`
...
phpcs-server_1       | 2018/03/08 05:25:05 Online Shop: Project checksum: `f8ac35b4ae08ab4969b67acc588807f8254d506ee578bf537c1017b7d9650ac4`
```
and 
```
lighthouse-server_1  | 2018/03/08 05:24:37 Custom Lite: Project checksum: `5485cb6c715b006295d6345d1fe96e3cafe7c2983ab50b485d9859180ed74983`
...
lighthouse-server_1  | 2018/03/08 05:25:13 i-amaze: Project checksum: `5485cb6c715b006295d6345d1fe96e3cafe7c2983ab50b485d9859180ed74983`
...
lighthouse-server_1  | 2018/03/08 05:25:40 Oceanica Lite: Project checksum: `5485cb6c715b006295d6345d1fe96e3cafe7c2983ab50b485d9859180ed74983`
```

As a result, only two audit posts show up in API. In this case for `i-amaze` and `Custom Lite`.

Expected result:

- Each project should have a unique checksum

- We should see 6 audit posts in API, one for each project. Or at least 5, in case the `i-amaze` project picked up by PHPCS and LH is actually the same project - note that the two checksums for `i-amaze` across the two servers are different as well.

**Comment by rheinardkorf** [comment]
@danlouw thanks for detailed breakdown. 

I will look at the pipeline today.  I am going to turn the `processMessage` func into a method of a new `struct` and remove some of the globals.  Without having inspected very closely yet, it looks like in some cases when ingest fails (which should cause a critical fail for the current pipeline) that it gets a previous value.

Using objects with props and methods should resolve this issue.

**Comment by rheinardkorf** [comment]
I believe this issue to be resolved.
