### ISSUE TITLE
Test the wp-specific ruleset

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#38]
Instructions on how to pull in the new wordpress.xwl file: https://github.com/wimg/PHPCompatibility#using-a-frameworkcms-specific-ruleset

We'll want to pull in the new code and replace the standard with the file in the cli command.

**Comment by valendesigns** [comment]
@rheinardkorf In the PHPCS Server if the type of project is a theme or plugin replace the standard with the ruleset file for WordPress.

**Comment by valendesigns** [comment]
`--standard=path/to/PHPCompatibility/framework-rulesets/framework-name.xml`

**Comment by rheinardkorf** [comment]
@valendesigns onto it... just need to work out how to do this in the phpcs-server and not in `pkg` as the message only gets received in the process. Mind is ticking....
