### ISSUE TITLE
Debug processing pipeline.

### ISSUE THREAD

**Issue by rheinardkorf** [wptide/wptide#56]
There are some issues with the processing pipeline as it passes a message down the pipeline. Here are some known cases...

1. The "Ingest" process that kicks it all off does not appear to send all messages to the next process.
This may well be related to the next issue (or even caused by the next issue).

2. The <processor>.Result object does not always seem to get passed from one process to the next.
Each process copies the original message, the result object and the path to files to be processed.  It seems like the message and path works correctly, but the results don't.
Relevant code is here: https://github.com/wptide/pkg/blob/refactor/pipeline/process/process.go#L72

Notes re the *.Results object. It first gets created here: https://github.com/wptide/pkg/blob/refactor/pipeline/process/ingest.go#L40

Issues with missing values have been identified by intercepting any of the processes using the `debug.go` process in go-tide.  Example usage.... https://github.com/xwp/go-tide/blob/pipeline/cmd/lighthouse-server/main.go#L208-L236

Need help to identify why Result is not preserved. This is why nothing is being written to the API because there is nothing to write.  The new error message processing for the pipe confirmed the issue as well by surfacing this error: https://github.com/wptide/pkg/blob/refactor/pipeline/payload/tide.go#L36  (i.e. the Results object was empty).

**Comment by rheinardkorf** [comment]
@DavidCramer hope this describes enough for you to take a look.

**Comment by DavidCramer** [comment]
@rheinardkorf that explains it very well thanks. And, that also explains why I couldn't get it working last week. I thought I missed something, but now I understand.

**Comment by DavidCramer** [comment]
@rheinardkorf is this still valid? looks like you resolved it already.
