### ISSUE TITLE
Research go-tide auditing errors

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#58]
### Description

1. setup Tide
2. run audits
3. turn on Sync Server, get audits in queue
4. let PHPCS/LH servers run
5. look through results for errors
6. document errors as GitHub Issues
7. research errors (as feasible)

**Comment by jeffpaul** [comment]
@DavidCramer as you get time, it would be immensely helpful to have your review of the new go-tide version of Tide to identify errors in the results so that the team can work through resolving those together.

**Comment by DavidCramer** [comment]
@jeffpaul I've been playing and making notes. So far I got for the initial setups and configs. I'll continue and document my findings.

**Comment by jeffpaul** [comment]
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1534882238000100) today, we're closing in favor of #145
