### ISSUE TITLE
Confirm license to use

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#6]
Currently showing MIT license, should this be GPLv2?
https://github.com/xwp/go-tide/blob/develop/LICENSE

**Comment by jeffpaul** [comment]
@lukecarbis with the Lighthouse integration being written in Go, a question exists as to the license to apply to this repo ([currently shown as MIT](https://github.com/xwp/go-tide/blob/develop/LICENSE)). Note that this repo is currently private, the rest of Tide is open sourced and licensed as GPLv2, and that the Go project is distributed under a [BSD-style license](https://golang.org/LICENSE). So, for the Lighthouse integration and this currently private repo, what should we license as? GPLv2? MIT? BSD-style? Other?

**Comment by rheinardkorf** [comment]
@jeffpaul I posted a comment in Slack re the licensing. I believe that GPL is not in our best interest for future derivative works or forks. We risk having to refactor any similar functionality again if we want to distribute it without source.

**Comment by jeffpaul** [comment]
Closing this with MIT license as the open source license to use.
