### ISSUE TITLE
API schema to match PHP Compat UX needs for .ORG

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#77]

**Comment by valendesigns** [comment]
We need to add warnings to the Parsed report in the PHPCS Server.

**Comment by jeffpaul** [comment]
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1534882540000100) today, we're tagging this to the `1.0.0` release

**Comment by jeffpaul** [comment]
Related to #152

**Comment by jeffpaul** [comment]
Note that this issue was [referenced in Slack](https://wordpress.slack.com/archives/C7TK8FBUJ/p1543353257096200).

**Comment by valendesigns** [comment]
This is going to need to wait unless @rheinardkorf can take a look and fix it on Monday. I took a look at it and discovered that the warnings are being included in the `errors` array in the parsed report, which means we need to ensure a few things happen to make this correct.

First wrap these line [phpcompatibility.go#L61-L97](https://github.com/wptide/pkg/blob/master/process/phpcs/phpcompatibility.go#L61-L97) with an if check like
```
if sniffMessage.Type == "ERROR" {
    // error code ...
} else {
    // warning code ...
}
```

Then create two new arrays `warning_map` and `warnings`. Some warnings are not specific to a PHP version or range and will need to be set to `all`.
