### ISSUE TITLE
HTTP Listener/Webhook on audit server(s)

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#84]
- [ ] An HTTP listener on each audit server, decoupling from a message queue.

**Comment by jeffpaul** [comment]
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1534882868000100) today, we're tagging this to `Future Release`

**Comment by valendesigns** [comment]
Out of scope for the project, we have the `GET` endpoint for the `wporg` user to request audits. Anything else is not needed.
