### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#86]
- [ ] Swagger or API blueprint (https://apiblueprint.org/, https://github.com/danielgtaylor/aglio, https://github.com/bukalapak/snowboard)
- [ ] convert to docs
- [ ] check that following the docs "works"
- [ ] Add link on demo website to GH readme for setup details
- [ ] Add link to GH readme to demo website for usage details

**Comment by jeffpaul** [comment]
Proposed docs site structure from @luboskmetko : https://docs.google.com/document/d/1gxLqj3yGoxcZBm_QeZHwcYnjtFflMcIZNBUO4gOLYME/edit?ts=5b114f0f

**Comment by jeffpaul** [comment]
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1534883155000100) today, we're tagging this to the `1.0.0` release

**Comment by jeffpaul** [comment]
Note that this issue was [referenced in Slack](https://wordpress.slack.com/archives/C7TK8FBUJ/p1543353412100600).

**Comment by valendesigns** [comment]
This is not needed
