### ISSUE TITLE
Account Sign Up with a way to get your API key/secret (no WP backend access)

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#89]

**Comment by hellofromtonya** [comment]
I would add that the way to get your API key/secret is _automatically_ generated to reduce latency and increase engagements and adoption.

As for managing API keys, I would suggest tying everything together into a Developer Portal.  That means empowering developers with all that each needs to utilize, contribute to, and build on top of Tide.  

One place (portal) increases the developer experience (DX).

**Comment by jeffpaul** [comment]
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1535486471000100) today, we're moving this to `Future Release`.
