### ISSUE TITLE
Finalize UX for .ORG integration

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#90]

**Comment by jeffpaul** [comment]
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1535486503000100) today, we're keeping this in the `1.0.0` release.

**Comment by jwold** [comment]
Is this related to the work with PHP compatibility, or is it a more broad issue?

**Comment by jeffpaul** [comment]
@jwold they're essentially the same issue, in different repos.  We can view https://github.com/wptide/tide-issues/issues/1 as the primary issue to track the work.

**Comment by jeffpaul** [comment]
Closing in favor of #152
