### ISSUE TITLE
.ORG integration with Webhook

### ISSUE THREAD

**Issue by jeffpaul** [wptide/wptide#91]
Handled via Meta team?

**Comment by jeffpaul** [comment]
Note that we're meeting with Otto this Friday afternoon CDT to discuss specifics of the .ORG integration and any changes needed on the Tide end to provide input to .ORG for a graceful integration. Updates to follow on details for the description of this issue.

**Comment by jeffpaul** [comment]
Once we have examples of hitting the API and some demo code, we'll want to email that to Otto and he'll start working on integration, test hits, and exposing the data to the plugin API.

**Comment by rheinardkorf** [comment]
@jeffpaul development is in progress.

**Comment by jeffpaul** [comment]
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1535486550000100) today, we're keeping this in the `1.0.0` release but that we'll need to update the integration plans as Tide's endpoints evolve.
