### ISSUE TITLE
Upgrade to Lighthouse v3.0.0

### ISSUE THREAD

**Issue by valendesigns** [wptide/wptide#92]
Lighthouse v3.0.0 has recently been released, we should upgrade Lighthouse and potentially Chromium. The Lighthouse Server image is built using stable Alpine 3.7 so the community repo is going to install [Chromium 61.0.3163.100-r0](https://pkgs.alpinelinux.org/package/v3.7/community/x86_64/chromium). However, if we want to upgrade to [Chromium 64.0.3282.168-r0](https://pkgs.alpinelinux.org/package/edge/community/x86_64/chromium) we'll need to upgrade Alpine to `edge`. It appears Lighthouse only requires Chromium 54 so we probably don't have to upgrade until stable Alpine 3.8.

Additionally, after doing the initial tests it's obvious that the json report output has also changed, more info [here](https://developers.google.com/web/tools/lighthouse/v3/migration) and [here](https://developers.google.com/web/updates/2018/05/lighthouse3), so we need to update the struct in [item.go#L112](https://github.com/wptide/pkg/blob/master/tide/item.go#L112) which now has a key of `categories` and not `reportCategories`. There could be other changes required, but this is the basic info to get started.

**Comment by jeffpaul** [comment]
@valendesigns does this really need to be in Tide v1.0? Couldn't we just wait on this since LHv3 is still in alpha and ship a Tide v1.x to include this? Trying to keep our scope for v1.0 as small as possible given our resources and time available.

**Comment by jeffpaul** [comment]
Note that we'll also need to update the `Running Lighthouse audits` docs given things change a bit with LHv3: https://github.com/xwp/go-tide/wiki/Running-Lighthouse-audits

**Comment by valendesigns** [comment]
@jeffpaul those docs need to be updated anyhow, they are out of date in not accurate anymore. I've actually completed the work required to upgrade to v3 in these two PRs https://github.com/xwp/go-tide/pull/93 and https://github.com/wptide/pkg/pull/10 so we don't need to wait until Lighthouse v3 stable to integrate into Tide now.
